name: example
description: Simple, single-class example exercising sudoku_api.
version: 2.0.0
homepage: https://github.com/AlvinRamoutar/sudoku-api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  sudoku_api: ^2.0.0

dev_dependencies:
  test: ^1.17.5
