name: sudoku
description: Sudoku!

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sudoku_solver_generator: ^2.1.0+1

  flutter_colorpicker: ^1.0.3

  # using a local copy to fix old dependency, until PR gets merged
  dynamic_color_theme:
    path: external/dynamic_color_theme

  system_theme: ^2.0.0

  shared_preferences: ^2.0.15
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

