name: sudoku
description: Sudoku!

publish_to: 'none'

version: 2.0.0+4

environment:
  sdk: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sudoku_solver_generator: ^2.1.0+1
  dynamic_color: ^1.8.1
  material_color_utilities: ^0.11.1
  flutter_colorpicker: ^1.1.0

  shared_preferences: ^2.0.15
  intl: ^0.20.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.1.14
  package_info_plus: ^8.3.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "assets/icon_background.png"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

