name: sudoku_api
description: sudoku_api simplifies the generation, interaction, and management of Sudoku Puzzles.
version: 2.0.0
homepage: https://github.com/AlvinRamoutar/sudoku-api

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  uuid: ^3.0.4
  tuple: ^2.0.0
  collection: ^1.15.0

dev_dependencies:
  test: ^1.17.5
